### ISSUE TITLE
Recommended code changes

### ISSUE THREAD

**Issue by lanking520** [CathyZhang0822/EmailBot#3]
Hi Cathy, I would like to propose some coding style changes and code changes

## General guideline

- [x] Please keep minimum line changes. Space between code should be either 1 or zero with reasons.

- [x] Please clean the order of of your [imported file](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L1-L8) into alphanumerical order

- [x] Please keep all self._ variable declared clearly at the beginning and identify if we are keeping them across the functions

- [x] Identify if some of the functions are helper function and should be set as private

- [x] Argument name should follow the general guidelines (such as this_is_my_args, Python people like this way. Java people like thisIsMyArgs)

- [x] Use Python coding style to add comments for functions

- [x] Use logger.info, logger.warning, logger.debug, logger.error to send information

## Specific questions

- [x] [Why clean_string is outside](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L16-L19)?
Consider add that as a private function in your class (_ underscore)

- [x] [Why 2015 as the general date](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L16-L19)
Use 1970-01-01 as Unix Epoch start date or initialize that into None
- [x] [A better name for `week`](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L35)
Can you change the week into a better name?
- [ ] [Error message?](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L47)
- [x] [Why -3](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L48)
Is `-3` a magic number, please add some comments here
- [ ] [Option on per page](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L59) Can we create an option here for customer to choose the number on their own?
- [x] [Change into boolean flag](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L56) Can you change this line into boolean type and change is name into some reasonable ones, such as `is_finished`

- [x] [Can you create a specific class type for these](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L89-L98) Can you put them all together into one class and return that in your function?

- [ ] [Generic helper functions](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L105-L106) Seen these lines appear a lot in your code, shall we put them all together into a helper function to make the code cleaner?

- [x] [change the variable name](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L140)

- [ ] [Wrap them up in a for loop](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L160-L163)

- [ ] [Add configurable variables](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L200) Can we add the variable here configurable in the function? Think you are a customer using this class, you do not want to dig into it and change the variable there

- [x] [Change into logger](https://github.com/CathyZhang0822/EmailBot/blob/master/EmailBot.py#L263)

Please leave your thoughts on these and use this as a checklist to mark as resolved.

**Comment by CathyZhang0822** [comment]
Clean the code a lot.
